/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnqui;

import javax.swing.JTextField;

/**
 *
 * @author Nacho
 */
public class LabPartidos2 extends javax.swing.JPanel {
     JTextField[][] partidos;
    /**
     * Creates new form LabPartidos2
     */
    public LabPartidos2() {
        initComponents();
        setpartidos();
    }

        public final void setpartidos(){
         partidos = new javax.swing.JTextField[][]{  {EquipoC1,EquipoV1},
            {EquipoC2,EquipoV2},
            {EquipoC3,EquipoV3},
            {EquipoC4,EquipoV4},
            {EquipoC5,EquipoV5},
            {EquipoC6,EquipoV6},
            {EquipoC7,EquipoV7},
            {EquipoC8,EquipoV8},
            {EquipoC9,EquipoV9},
            {EquipoC10,EquipoV10},
            {EquipoC11,EquipoV11},
            {EquipoC12,EquipoV12},
            {EquipoC13,EquipoV13},
            {EquipoC14,EquipoV14}};
    
    }
        
    public void setPartidos(int j, int i, String equipo){

            partidos[j][i].setText(equipo);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EquipoC11 = new javax.swing.JTextField();
        EquipoV11 = new javax.swing.JTextField();
        EquipoC12 = new javax.swing.JTextField();
        EquipoV12 = new javax.swing.JTextField();
        EquipoC13 = new javax.swing.JTextField();
        EquipoV13 = new javax.swing.JTextField();
        EquipoC14 = new javax.swing.JTextField();
        EquipoV14 = new javax.swing.JTextField();
        EquipoV7 = new javax.swing.JTextField();
        EquipoV2 = new javax.swing.JTextField();
        EquipoC8 = new javax.swing.JTextField();
        EquipoV8 = new javax.swing.JTextField();
        EquipoC9 = new javax.swing.JTextField();
        EquipoC3 = new javax.swing.JTextField();
        EquipoV9 = new javax.swing.JTextField();
        EquipoV3 = new javax.swing.JTextField();
        EquipoC10 = new javax.swing.JTextField();
        EquipoC4 = new javax.swing.JTextField();
        EquipoC5 = new javax.swing.JTextField();
        EquipoV5 = new javax.swing.JTextField();
        EquipoC1 = new javax.swing.JTextField();
        EquipoC6 = new javax.swing.JTextField();
        EquipoV6 = new javax.swing.JTextField();
        EquipoV1 = new javax.swing.JTextField();
        EquipoC7 = new javax.swing.JTextField();
        EquipoC2 = new javax.swing.JTextField();
        EquipoV10 = new javax.swing.JTextField();
        EquipoV4 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(230, 250));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        EquipoC11.setEditable(false);
        EquipoC11.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC11.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC11.setBorder(null);
        EquipoC11.setFocusable(false);
        EquipoC11.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC11.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC11ActionPerformed(evt);
            }
        });

        EquipoV11.setEditable(false);
        EquipoV11.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV11.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV11.setBorder(null);
        EquipoV11.setFocusable(false);
        EquipoV11.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV11.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV11ActionPerformed(evt);
            }
        });

        EquipoC12.setEditable(false);
        EquipoC12.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC12.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC12.setBorder(null);
        EquipoC12.setFocusable(false);
        EquipoC12.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC12.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC12ActionPerformed(evt);
            }
        });

        EquipoV12.setEditable(false);
        EquipoV12.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV12.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV12.setBorder(null);
        EquipoV12.setFocusable(false);
        EquipoV12.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV12.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV12ActionPerformed(evt);
            }
        });

        EquipoC13.setEditable(false);
        EquipoC13.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC13.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC13.setBorder(null);
        EquipoC13.setFocusable(false);
        EquipoC13.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC13.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC13ActionPerformed(evt);
            }
        });

        EquipoV13.setEditable(false);
        EquipoV13.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV13.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV13.setBorder(null);
        EquipoV13.setFocusable(false);
        EquipoV13.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV13.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV13ActionPerformed(evt);
            }
        });

        EquipoC14.setEditable(false);
        EquipoC14.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC14.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC14.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC14.setBorder(null);
        EquipoC14.setFocusable(false);
        EquipoC14.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC14.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC14ActionPerformed(evt);
            }
        });

        EquipoV14.setEditable(false);
        EquipoV14.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV14.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV14.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV14.setBorder(null);
        EquipoV14.setFocusable(false);
        EquipoV14.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV14.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV14ActionPerformed(evt);
            }
        });

        EquipoV7.setEditable(false);
        EquipoV7.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV7.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV7.setBorder(null);
        EquipoV7.setFocusable(false);
        EquipoV7.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV7.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV7ActionPerformed(evt);
            }
        });

        EquipoV2.setEditable(false);
        EquipoV2.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV2.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV2.setBorder(null);
        EquipoV2.setFocusable(false);
        EquipoV2.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV2.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV2ActionPerformed(evt);
            }
        });

        EquipoC8.setEditable(false);
        EquipoC8.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC8.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC8.setBorder(null);
        EquipoC8.setFocusable(false);
        EquipoC8.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC8.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC8ActionPerformed(evt);
            }
        });

        EquipoV8.setEditable(false);
        EquipoV8.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV8.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV8.setBorder(null);
        EquipoV8.setFocusable(false);
        EquipoV8.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV8.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV8ActionPerformed(evt);
            }
        });

        EquipoC9.setEditable(false);
        EquipoC9.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC9.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC9.setBorder(null);
        EquipoC9.setFocusable(false);
        EquipoC9.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC9.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC9ActionPerformed(evt);
            }
        });

        EquipoC3.setEditable(false);
        EquipoC3.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC3.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC3.setBorder(null);
        EquipoC3.setFocusable(false);
        EquipoC3.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC3.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC3ActionPerformed(evt);
            }
        });

        EquipoV9.setEditable(false);
        EquipoV9.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV9.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV9.setBorder(null);
        EquipoV9.setFocusable(false);
        EquipoV9.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV9.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV9ActionPerformed(evt);
            }
        });

        EquipoV3.setEditable(false);
        EquipoV3.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV3.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV3.setBorder(null);
        EquipoV3.setFocusable(false);
        EquipoV3.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV3.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV3ActionPerformed(evt);
            }
        });

        EquipoC10.setEditable(false);
        EquipoC10.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC10.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC10.setBorder(null);
        EquipoC10.setFocusable(false);
        EquipoC10.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC10.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC10ActionPerformed(evt);
            }
        });

        EquipoC4.setEditable(false);
        EquipoC4.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC4.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC4.setBorder(null);
        EquipoC4.setFocusable(false);
        EquipoC4.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC4.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC4ActionPerformed(evt);
            }
        });

        EquipoC5.setEditable(false);
        EquipoC5.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC5.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC5.setBorder(null);
        EquipoC5.setFocusable(false);
        EquipoC5.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC5.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC5ActionPerformed(evt);
            }
        });

        EquipoV5.setEditable(false);
        EquipoV5.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV5.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV5.setBorder(null);
        EquipoV5.setFocusable(false);
        EquipoV5.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV5.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV5ActionPerformed(evt);
            }
        });

        EquipoC1.setEditable(false);
        EquipoC1.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC1.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC1.setBorder(null);
        EquipoC1.setFocusable(false);
        EquipoC1.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC1.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC1ActionPerformed(evt);
            }
        });

        EquipoC6.setEditable(false);
        EquipoC6.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC6.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC6.setBorder(null);
        EquipoC6.setFocusable(false);
        EquipoC6.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC6.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC6ActionPerformed(evt);
            }
        });

        EquipoV6.setEditable(false);
        EquipoV6.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV6.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV6.setBorder(null);
        EquipoV6.setFocusable(false);
        EquipoV6.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV6.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV6ActionPerformed(evt);
            }
        });

        EquipoV1.setEditable(false);
        EquipoV1.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV1.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV1.setBorder(null);
        EquipoV1.setFocusable(false);
        EquipoV1.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV1.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV1ActionPerformed(evt);
            }
        });

        EquipoC7.setEditable(false);
        EquipoC7.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC7.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC7.setBorder(null);
        EquipoC7.setFocusable(false);
        EquipoC7.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC7.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC7ActionPerformed(evt);
            }
        });

        EquipoC2.setEditable(false);
        EquipoC2.setBackground(new java.awt.Color(255, 255, 204));
        EquipoC2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoC2.setForeground(new java.awt.Color(102, 102, 102));
        EquipoC2.setBorder(null);
        EquipoC2.setFocusable(false);
        EquipoC2.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoC2.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoC2ActionPerformed(evt);
            }
        });

        EquipoV10.setEditable(false);
        EquipoV10.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV10.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV10.setBorder(null);
        EquipoV10.setFocusable(false);
        EquipoV10.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV10.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV10ActionPerformed(evt);
            }
        });

        EquipoV4.setEditable(false);
        EquipoV4.setBackground(new java.awt.Color(255, 255, 204));
        EquipoV4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        EquipoV4.setForeground(new java.awt.Color(102, 102, 102));
        EquipoV4.setBorder(null);
        EquipoV4.setFocusable(false);
        EquipoV4.setMargin(new java.awt.Insets(6, 4, 2, 2));
        EquipoV4.setSelectionColor(new java.awt.Color(102, 102, 102));
        EquipoV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoV4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EquipoC14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EquipoV14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EquipoC13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EquipoV13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoC4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EquipoC6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoC7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoC9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoC11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EquipoC13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoV14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EquipoC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC5ActionPerformed

    private void EquipoV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV5ActionPerformed

    private void EquipoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC1ActionPerformed

    private void EquipoC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC6ActionPerformed

    private void EquipoV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV6ActionPerformed

    private void EquipoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV1ActionPerformed

    private void EquipoC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC7ActionPerformed

    private void EquipoC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC2ActionPerformed

    private void EquipoV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV7ActionPerformed

    private void EquipoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV2ActionPerformed

    private void EquipoC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC8ActionPerformed

    private void EquipoV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV8ActionPerformed

    private void EquipoC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC9ActionPerformed

    private void EquipoC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC3ActionPerformed

    private void EquipoV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV9ActionPerformed

    private void EquipoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV3ActionPerformed

    private void EquipoC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC10ActionPerformed

    private void EquipoC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC4ActionPerformed

    private void EquipoV10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV10ActionPerformed

    private void EquipoV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV4ActionPerformed

    private void EquipoC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC11ActionPerformed

    private void EquipoV11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV11ActionPerformed

    private void EquipoC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC12ActionPerformed

    private void EquipoV12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV12ActionPerformed

    private void EquipoC13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC13ActionPerformed

    private void EquipoV13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV13ActionPerformed

    private void EquipoC14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoC14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoC14ActionPerformed

    private void EquipoV14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoV14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoV14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EquipoC1;
    private javax.swing.JTextField EquipoC10;
    private javax.swing.JTextField EquipoC11;
    private javax.swing.JTextField EquipoC12;
    private javax.swing.JTextField EquipoC13;
    private javax.swing.JTextField EquipoC14;
    private javax.swing.JTextField EquipoC2;
    private javax.swing.JTextField EquipoC3;
    private javax.swing.JTextField EquipoC4;
    private javax.swing.JTextField EquipoC5;
    private javax.swing.JTextField EquipoC6;
    private javax.swing.JTextField EquipoC7;
    private javax.swing.JTextField EquipoC8;
    private javax.swing.JTextField EquipoC9;
    private javax.swing.JTextField EquipoV1;
    private javax.swing.JTextField EquipoV10;
    private javax.swing.JTextField EquipoV11;
    private javax.swing.JTextField EquipoV12;
    private javax.swing.JTextField EquipoV13;
    private javax.swing.JTextField EquipoV14;
    private javax.swing.JTextField EquipoV2;
    private javax.swing.JTextField EquipoV3;
    private javax.swing.JTextField EquipoV4;
    private javax.swing.JTextField EquipoV5;
    private javax.swing.JTextField EquipoV6;
    private javax.swing.JTextField EquipoV7;
    private javax.swing.JTextField EquipoV8;
    private javax.swing.JTextField EquipoV9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
