/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnqui;

import java.awt.Label;
        
/**
 *
 * @author igfernan
 */
public class LabPartidos extends javax.swing.JPanel {
    public Label[][] partidos;  
    /**
     * Creates new form LabPartidos
     */
    public LabPartidos() {
        initComponents();
       
        setpartidos();
    }
    
    
    public final void setpartidos(){
         partidos = new java.awt.Label[][]{  {EquipoC1,EquipoV1},
                                                        {EquipoC2,EquipoV2},
                                                        {EquipoC3,EquipoV3},
                                                        {EquipoC4,EquipoV4},
                                                        {EquipoC5,EquipoV5},
                                                        {EquipoC6,EquipoV6},
                                                        {EquipoC7,EquipoV7},
                                                        {EquipoC8,EquipoV8},
                                                        {EquipoC9,EquipoV9},
                                                        {EquipoC10,EquipoV10},
                                                        {EquipoC11,EquipoV11},
                                                        {EquipoC12,EquipoV12},
                                                        {EquipoC13,EquipoV13},
                                                        {EquipoC14,EquipoV14}};
    
    }
    /**
     *
     * @param i --> Columna
     * @param j --> Fila
     * @param equipo
     */
    public void setPartidos(int j, int i, String equipo){

            partidos[j][i].setText(equipo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EquipoV9 = new java.awt.Label();
        EquipoC9 = new java.awt.Label();
        EquipoV10 = new java.awt.Label();
        EquipoC10 = new java.awt.Label();
        EquipoV11 = new java.awt.Label();
        EquipoC11 = new java.awt.Label();
        EquipoV12 = new java.awt.Label();
        EquipoC12 = new java.awt.Label();
        EquipoV13 = new java.awt.Label();
        EquipoC1 = new java.awt.Label();
        EquipoC13 = new java.awt.Label();
        EquipoV14 = new java.awt.Label();
        EquipoC14 = new java.awt.Label();
        EquipoV1 = new java.awt.Label();
        EquipoC2 = new java.awt.Label();
        EquipoV2 = new java.awt.Label();
        EquipoC3 = new java.awt.Label();
        EquipoV3 = new java.awt.Label();
        EquipoC4 = new java.awt.Label();
        EquipoV4 = new java.awt.Label();
        EquipoC5 = new java.awt.Label();
        EquipoV5 = new java.awt.Label();
        EquipoC6 = new java.awt.Label();
        EquipoV6 = new java.awt.Label();
        EquipoC7 = new java.awt.Label();
        EquipoV7 = new java.awt.Label();
        EquipoV8 = new java.awt.Label();
        EquipoC8 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        label43 = new java.awt.Label();
        label44 = new java.awt.Label();
        label45 = new java.awt.Label();
        label46 = new java.awt.Label();
        label47 = new java.awt.Label();
        label48 = new java.awt.Label();
        label49 = new java.awt.Label();
        label50 = new java.awt.Label();
        label51 = new java.awt.Label();
        label52 = new java.awt.Label();
        label53 = new java.awt.Label();
        label54 = new java.awt.Label();
        label55 = new java.awt.Label();
        label56 = new java.awt.Label();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        EquipoV9.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV9.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV9.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV9.setName(""); // NOI18N
        EquipoV9.setText(" ");

        EquipoC9.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC9.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC9.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC9.setName(""); // NOI18N
        EquipoC9.setText(" ");

        EquipoV10.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV10.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV10.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV10.setName(""); // NOI18N
        EquipoV10.setText(" ");

        EquipoC10.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC10.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC10.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC10.setName(""); // NOI18N
        EquipoC10.setText(" ");

        EquipoV11.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV11.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV11.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV11.setName(""); // NOI18N
        EquipoV11.setText(" ");

        EquipoC11.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC11.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC11.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC11.setName(""); // NOI18N
        EquipoC11.setText(" ");

        EquipoV12.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV12.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV12.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV12.setName(""); // NOI18N
        EquipoV12.setText(" ");

        EquipoC12.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC12.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC12.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC12.setName(""); // NOI18N
        EquipoC12.setText(" ");

        EquipoV13.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV13.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV13.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV13.setName(""); // NOI18N
        EquipoV13.setText(" ");

        EquipoC1.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC1.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC1.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC1.setName(""); // NOI18N
        EquipoC1.setText(" ");

        EquipoC13.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC13.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC13.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC13.setName(""); // NOI18N
        EquipoC13.setText(" ");

        EquipoV14.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV14.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV14.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV14.setName(""); // NOI18N
        EquipoV14.setText(" ");

        EquipoC14.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC14.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC14.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC14.setName(""); // NOI18N
        EquipoC14.setText(" ");

        EquipoV1.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV1.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV1.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV1.setName(""); // NOI18N
        EquipoV1.setText(" ");

        EquipoC2.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC2.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC2.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC2.setName(""); // NOI18N
        EquipoC2.setText(" ");

        EquipoV2.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV2.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV2.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV2.setName(""); // NOI18N
        EquipoV2.setText(" ");

        EquipoC3.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC3.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC3.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC3.setName(""); // NOI18N
        EquipoC3.setText(" ");

        EquipoV3.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV3.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV3.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV3.setName(""); // NOI18N
        EquipoV3.setText(" ");

        EquipoC4.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC4.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC4.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC4.setName(""); // NOI18N
        EquipoC4.setText(" ");

        EquipoV4.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV4.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV4.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV4.setName(""); // NOI18N
        EquipoV4.setText(" ");

        EquipoC5.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC5.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC5.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC5.setName(""); // NOI18N
        EquipoC5.setText(" ");

        EquipoV5.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV5.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV5.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV5.setName(""); // NOI18N
        EquipoV5.setText(" ");

        EquipoC6.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC6.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC6.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC6.setName(""); // NOI18N
        EquipoC6.setText(" ");

        EquipoV6.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV6.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV6.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV6.setName(""); // NOI18N
        EquipoV6.setText(" ");

        EquipoC7.setBackground(new java.awt.Color(244, 244, 244));
        EquipoC7.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC7.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC7.setName(""); // NOI18N
        EquipoC7.setText(" ");

        EquipoV7.setBackground(new java.awt.Color(244, 244, 244));
        EquipoV7.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV7.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV7.setName(""); // NOI18N
        EquipoV7.setText(" ");

        EquipoV8.setBackground(new java.awt.Color(255, 255, 255));
        EquipoV8.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoV8.setForeground(new java.awt.Color(0, 0, 51));
        EquipoV8.setName(""); // NOI18N
        EquipoV8.setText(" ");

        EquipoC8.setBackground(new java.awt.Color(255, 255, 255));
        EquipoC8.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        EquipoC8.setForeground(new java.awt.Color(0, 0, 51));
        EquipoC8.setName(""); // NOI18N
        EquipoC8.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoC14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EquipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EquipoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EquipoC3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoC4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoC6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoC9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoC12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoC13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EquipoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EquipoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(EquipoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EquipoV4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(EquipoV5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(EquipoV6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EquipoV7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EquipoV8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(EquipoV9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EquipoV10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoV11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(EquipoV12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EquipoV13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EquipoV14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipoC14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipoV14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        label43.setAlignment(java.awt.Label.RIGHT);
        label43.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label43.setForeground(new java.awt.Color(102, 102, 102));
        label43.setName(""); // NOI18N
        label43.setPreferredSize(new java.awt.Dimension(10, 17));
        label43.setText("1");

        label44.setAlignment(java.awt.Label.RIGHT);
        label44.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label44.setForeground(new java.awt.Color(102, 102, 102));
        label44.setName(""); // NOI18N
        label44.setText("2");

        label45.setAlignment(java.awt.Label.RIGHT);
        label45.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label45.setForeground(new java.awt.Color(102, 102, 102));
        label45.setName(""); // NOI18N
        label45.setPreferredSize(new java.awt.Dimension(10, 17));
        label45.setText("3");

        label46.setAlignment(java.awt.Label.RIGHT);
        label46.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label46.setForeground(new java.awt.Color(102, 102, 102));
        label46.setName(""); // NOI18N
        label46.setText("4");

        label47.setAlignment(java.awt.Label.RIGHT);
        label47.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label47.setForeground(new java.awt.Color(102, 102, 102));
        label47.setName(""); // NOI18N
        label47.setText("5");

        label48.setAlignment(java.awt.Label.RIGHT);
        label48.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label48.setForeground(new java.awt.Color(102, 102, 102));
        label48.setName(""); // NOI18N
        label48.setText("6");

        label49.setAlignment(java.awt.Label.RIGHT);
        label49.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label49.setForeground(new java.awt.Color(102, 102, 102));
        label49.setName(""); // NOI18N
        label49.setText("7");

        label50.setAlignment(java.awt.Label.RIGHT);
        label50.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label50.setForeground(new java.awt.Color(102, 102, 102));
        label50.setName(""); // NOI18N
        label50.setText("8");

        label51.setAlignment(java.awt.Label.RIGHT);
        label51.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label51.setForeground(new java.awt.Color(102, 102, 102));
        label51.setName(""); // NOI18N
        label51.setText("9");

        label52.setAlignment(java.awt.Label.RIGHT);
        label52.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label52.setForeground(new java.awt.Color(102, 102, 102));
        label52.setName(""); // NOI18N
        label52.setPreferredSize(new java.awt.Dimension(10, 17));
        label52.setText("10");

        label53.setAlignment(java.awt.Label.RIGHT);
        label53.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label53.setForeground(new java.awt.Color(102, 102, 102));
        label53.setName(""); // NOI18N
        label53.setPreferredSize(new java.awt.Dimension(10, 17));
        label53.setText("11");

        label54.setAlignment(java.awt.Label.RIGHT);
        label54.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label54.setForeground(new java.awt.Color(102, 102, 102));
        label54.setName(""); // NOI18N
        label54.setPreferredSize(new java.awt.Dimension(10, 17));
        label54.setText("12");

        label55.setAlignment(java.awt.Label.RIGHT);
        label55.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label55.setForeground(new java.awt.Color(102, 102, 102));
        label55.setName(""); // NOI18N
        label55.setPreferredSize(new java.awt.Dimension(10, 17));
        label55.setText("13");

        label56.setAlignment(java.awt.Label.RIGHT);
        label56.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        label56.setForeground(new java.awt.Color(102, 102, 102));
        label56.setName(""); // NOI18N
        label56.setPreferredSize(new java.awt.Dimension(10, 17));
        label56.setText("14");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label56, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label55, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(label45, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(label46, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                        .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(16, 16, 16))
                                                    .addComponent(label52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(16, 16, 16))
                                            .addComponent(label53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addComponent(label54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addComponent(label55, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addComponent(label56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label EquipoC1;
    private java.awt.Label EquipoC10;
    private java.awt.Label EquipoC11;
    private java.awt.Label EquipoC12;
    private java.awt.Label EquipoC13;
    private java.awt.Label EquipoC14;
    private java.awt.Label EquipoC2;
    private java.awt.Label EquipoC3;
    private java.awt.Label EquipoC4;
    private java.awt.Label EquipoC5;
    private java.awt.Label EquipoC6;
    private java.awt.Label EquipoC7;
    private java.awt.Label EquipoC8;
    private java.awt.Label EquipoC9;
    private java.awt.Label EquipoV1;
    private java.awt.Label EquipoV10;
    private java.awt.Label EquipoV11;
    private java.awt.Label EquipoV12;
    private java.awt.Label EquipoV13;
    private java.awt.Label EquipoV14;
    private java.awt.Label EquipoV2;
    private java.awt.Label EquipoV3;
    private java.awt.Label EquipoV4;
    private java.awt.Label EquipoV5;
    private java.awt.Label EquipoV6;
    private java.awt.Label EquipoV7;
    private java.awt.Label EquipoV8;
    private java.awt.Label EquipoV9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label50;
    private java.awt.Label label51;
    private java.awt.Label label52;
    private java.awt.Label label53;
    private java.awt.Label label54;
    private java.awt.Label label55;
    private java.awt.Label label56;
    // End of variables declaration//GEN-END:variables
}
