/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnqui;

import java.awt.Color;

/**
 *
 * @author igfernan
 */
public class LabResult extends javax.swing.JPanel {
    Color negro = new Color(0,0,0);
    Color rosa = new Color(255,199,199);
    /**
     * Creates new form LabResult
     */
    public LabResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Pro_g_4 = new javax.swing.JLabel();
        Pro_g_5 = new javax.swing.JLabel();
        Pro_g_6 = new javax.swing.JLabel();
        Pro_g_7 = new javax.swing.JLabel();
        Pro_g_8 = new javax.swing.JLabel();
        Pro_g_9 = new javax.swing.JLabel();
        Pro_g_10 = new javax.swing.JLabel();
        Pro_g_11 = new javax.swing.JLabel();
        Pro_g_32 = new javax.swing.JLabel();
        Pro_g_12 = new javax.swing.JLabel();
        Pro_g_33 = new javax.swing.JLabel();
        Pro_g_34 = new javax.swing.JLabel();
        Pro_g_35 = new javax.swing.JLabel();
        Pro_g_36 = new javax.swing.JLabel();
        Pro_g_37 = new javax.swing.JLabel();
        Pro_g_38 = new javax.swing.JLabel();
        Pro_g_39 = new javax.swing.JLabel();
        Pro_g_40 = new javax.swing.JLabel();
        Pro_g_41 = new javax.swing.JLabel();
        Pro_g_42 = new javax.swing.JLabel();
        Pro_g_2 = new javax.swing.JLabel();
        Pro_g_13 = new javax.swing.JLabel();
        Pro_g_14 = new javax.swing.JLabel();
        Pro_g_15 = new javax.swing.JLabel();
        Pro_g_16 = new javax.swing.JLabel();
        Pro_g_17 = new javax.swing.JLabel();
        Pro_g_18 = new javax.swing.JLabel();
        Pro_g_19 = new javax.swing.JLabel();
        Pro_g_20 = new javax.swing.JLabel();
        Pro_g_21 = new javax.swing.JLabel();
        Pro_g_22 = new javax.swing.JLabel();
        Pro_g_1 = new javax.swing.JLabel();
        Pro_g_23 = new javax.swing.JLabel();
        Pro_g_3 = new javax.swing.JLabel();
        Pro_g_24 = new javax.swing.JLabel();
        Pro_g_25 = new javax.swing.JLabel();
        Pro_g_26 = new javax.swing.JLabel();
        Pro_g_27 = new javax.swing.JLabel();
        Pro_g_28 = new javax.swing.JLabel();
        Pro_g_29 = new javax.swing.JLabel();
        Pro_g_30 = new javax.swing.JLabel();
        Pro_g_31 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        Pro_g_4.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_4.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_4.setText("1");
        Pro_g_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_4.setFocusable(false);
        Pro_g_4.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_4.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_4.setOpaque(true);
        Pro_g_4.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_4.setRequestFocusEnabled(false);
        Pro_g_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_4MouseClicked(evt);
            }
        });

        Pro_g_5.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_5.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_5.setText("X");
        Pro_g_5.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_5.setFocusable(false);
        Pro_g_5.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_5.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_5.setOpaque(true);
        Pro_g_5.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_5.setRequestFocusEnabled(false);
        Pro_g_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_5MouseClicked(evt);
            }
        });

        Pro_g_6.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_6.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_6.setText("2");
        Pro_g_6.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_6.setFocusable(false);
        Pro_g_6.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_6.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_6.setOpaque(true);
        Pro_g_6.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_6.setRequestFocusEnabled(false);
        Pro_g_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_6MouseClicked(evt);
            }
        });

        Pro_g_7.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_7.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_7.setText("1");
        Pro_g_7.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_7.setFocusable(false);
        Pro_g_7.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_7.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_7.setOpaque(true);
        Pro_g_7.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_7.setRequestFocusEnabled(false);
        Pro_g_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_7MouseClicked(evt);
            }
        });

        Pro_g_8.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_8.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_8.setText("X");
        Pro_g_8.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_8.setFocusable(false);
        Pro_g_8.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_8.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_8.setOpaque(true);
        Pro_g_8.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_8.setRequestFocusEnabled(false);
        Pro_g_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_8MouseClicked(evt);
            }
        });

        Pro_g_9.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_9.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_9.setText("2");
        Pro_g_9.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_9.setFocusable(false);
        Pro_g_9.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_9.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_9.setOpaque(true);
        Pro_g_9.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_9.setRequestFocusEnabled(false);
        Pro_g_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_9MouseClicked(evt);
            }
        });

        Pro_g_10.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_10.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_10.setText("1");
        Pro_g_10.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_10.setFocusable(false);
        Pro_g_10.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_10.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_10.setOpaque(true);
        Pro_g_10.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_10.setRequestFocusEnabled(false);
        Pro_g_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_10MouseClicked(evt);
            }
        });

        Pro_g_11.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_11.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_11.setText("X");
        Pro_g_11.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_11.setFocusable(false);
        Pro_g_11.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_11.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_11.setOpaque(true);
        Pro_g_11.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_11.setRequestFocusEnabled(false);
        Pro_g_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_11MouseClicked(evt);
            }
        });

        Pro_g_32.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_32.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_32.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_32.setText("X");
        Pro_g_32.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_32.setFocusable(false);
        Pro_g_32.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_32.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_32.setOpaque(true);
        Pro_g_32.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_32.setRequestFocusEnabled(false);
        Pro_g_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_32MouseClicked(evt);
            }
        });

        Pro_g_12.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_12.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_12.setText("2");
        Pro_g_12.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_12.setFocusable(false);
        Pro_g_12.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_12.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_12.setOpaque(true);
        Pro_g_12.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_12.setRequestFocusEnabled(false);
        Pro_g_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_12MouseClicked(evt);
            }
        });

        Pro_g_33.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_33.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_33.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_33.setText("2");
        Pro_g_33.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_33.setFocusable(false);
        Pro_g_33.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_33.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_33.setOpaque(true);
        Pro_g_33.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_33.setRequestFocusEnabled(false);
        Pro_g_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_33MouseClicked(evt);
            }
        });

        Pro_g_34.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_34.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_34.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_34.setText("1");
        Pro_g_34.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_34.setFocusable(false);
        Pro_g_34.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_34.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_34.setOpaque(true);
        Pro_g_34.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_34.setRequestFocusEnabled(false);
        Pro_g_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_34MouseClicked(evt);
            }
        });

        Pro_g_35.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_35.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_35.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_35.setText("X");
        Pro_g_35.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_35.setFocusable(false);
        Pro_g_35.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_35.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_35.setOpaque(true);
        Pro_g_35.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_35.setRequestFocusEnabled(false);
        Pro_g_35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_35MouseClicked(evt);
            }
        });

        Pro_g_36.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_36.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_36.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_36.setText("2");
        Pro_g_36.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_36.setFocusable(false);
        Pro_g_36.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_36.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_36.setOpaque(true);
        Pro_g_36.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_36.setRequestFocusEnabled(false);
        Pro_g_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_36MouseClicked(evt);
            }
        });

        Pro_g_37.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_37.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_37.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_37.setText("1");
        Pro_g_37.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_37.setFocusable(false);
        Pro_g_37.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_37.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_37.setOpaque(true);
        Pro_g_37.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_37.setRequestFocusEnabled(false);
        Pro_g_37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_37MouseClicked(evt);
            }
        });

        Pro_g_38.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_38.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_38.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_38.setText("X");
        Pro_g_38.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_38.setFocusable(false);
        Pro_g_38.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_38.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_38.setOpaque(true);
        Pro_g_38.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_38.setRequestFocusEnabled(false);
        Pro_g_38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_38MouseClicked(evt);
            }
        });

        Pro_g_39.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_39.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_39.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_39.setText("2");
        Pro_g_39.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_39.setFocusable(false);
        Pro_g_39.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_39.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_39.setOpaque(true);
        Pro_g_39.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_39.setRequestFocusEnabled(false);
        Pro_g_39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_39MouseClicked(evt);
            }
        });

        Pro_g_40.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_40.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_40.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_40.setText("1");
        Pro_g_40.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_40.setFocusable(false);
        Pro_g_40.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_40.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_40.setOpaque(true);
        Pro_g_40.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_40.setRequestFocusEnabled(false);
        Pro_g_40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_40MouseClicked(evt);
            }
        });

        Pro_g_41.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_41.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_41.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_41.setText("X");
        Pro_g_41.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_41.setFocusable(false);
        Pro_g_41.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_41.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_41.setOpaque(true);
        Pro_g_41.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_41.setRequestFocusEnabled(false);
        Pro_g_41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_41MouseClicked(evt);
            }
        });

        Pro_g_42.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_42.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_42.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_42.setText("2");
        Pro_g_42.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_42.setFocusable(false);
        Pro_g_42.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_42.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_42.setOpaque(true);
        Pro_g_42.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_42.setRequestFocusEnabled(false);
        Pro_g_42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_42MouseClicked(evt);
            }
        });

        Pro_g_2.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_2.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_2.setText("X");
        Pro_g_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_2.setFocusable(false);
        Pro_g_2.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_2.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_2.setOpaque(true);
        Pro_g_2.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_2.setRequestFocusEnabled(false);
        Pro_g_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_2MouseClicked(evt);
            }
        });

        Pro_g_13.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_13.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_13.setText("1");
        Pro_g_13.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_13.setFocusable(false);
        Pro_g_13.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_13.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_13.setOpaque(true);
        Pro_g_13.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_13.setRequestFocusEnabled(false);
        Pro_g_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_13MouseClicked(evt);
            }
        });

        Pro_g_14.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_14.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_14.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_14.setText("X");
        Pro_g_14.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_14.setFocusable(false);
        Pro_g_14.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_14.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_14.setOpaque(true);
        Pro_g_14.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_14.setRequestFocusEnabled(false);
        Pro_g_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_14MouseClicked(evt);
            }
        });

        Pro_g_15.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_15.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_15.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_15.setText("2");
        Pro_g_15.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_15.setFocusable(false);
        Pro_g_15.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_15.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_15.setOpaque(true);
        Pro_g_15.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_15.setRequestFocusEnabled(false);
        Pro_g_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_15MouseClicked(evt);
            }
        });

        Pro_g_16.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_16.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_16.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_16.setText("1");
        Pro_g_16.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_16.setFocusable(false);
        Pro_g_16.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_16.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_16.setOpaque(true);
        Pro_g_16.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_16.setRequestFocusEnabled(false);
        Pro_g_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_16MouseClicked(evt);
            }
        });

        Pro_g_17.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_17.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_17.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_17.setText("X");
        Pro_g_17.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_17.setFocusable(false);
        Pro_g_17.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_17.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_17.setOpaque(true);
        Pro_g_17.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_17.setRequestFocusEnabled(false);
        Pro_g_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_17MouseClicked(evt);
            }
        });

        Pro_g_18.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_18.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_18.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_18.setText("2");
        Pro_g_18.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_18.setFocusable(false);
        Pro_g_18.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_18.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_18.setOpaque(true);
        Pro_g_18.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_18.setRequestFocusEnabled(false);
        Pro_g_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_18MouseClicked(evt);
            }
        });

        Pro_g_19.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_19.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_19.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_19.setText("1");
        Pro_g_19.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_19.setFocusable(false);
        Pro_g_19.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_19.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_19.setOpaque(true);
        Pro_g_19.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_19.setRequestFocusEnabled(false);
        Pro_g_19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_19MouseClicked(evt);
            }
        });

        Pro_g_20.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_20.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_20.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_20.setText("X");
        Pro_g_20.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_20.setFocusable(false);
        Pro_g_20.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_20.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_20.setOpaque(true);
        Pro_g_20.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_20.setRequestFocusEnabled(false);
        Pro_g_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_20MouseClicked(evt);
            }
        });

        Pro_g_21.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_21.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_21.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_21.setText("2");
        Pro_g_21.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_21.setFocusable(false);
        Pro_g_21.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_21.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_21.setOpaque(true);
        Pro_g_21.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_21.setRequestFocusEnabled(false);
        Pro_g_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_21MouseClicked(evt);
            }
        });

        Pro_g_22.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_22.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_22.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_22.setText("1");
        Pro_g_22.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_22.setFocusable(false);
        Pro_g_22.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_22.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_22.setOpaque(true);
        Pro_g_22.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_22.setRequestFocusEnabled(false);
        Pro_g_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_22MouseClicked(evt);
            }
        });

        Pro_g_1.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_1.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_1.setText("1");
        Pro_g_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_1.setFocusable(false);
        Pro_g_1.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_1.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_1.setOpaque(true);
        Pro_g_1.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_1.setRequestFocusEnabled(false);
        Pro_g_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_1MouseClicked(evt);
            }
        });

        Pro_g_23.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_23.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_23.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_23.setText("X");
        Pro_g_23.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_23.setFocusable(false);
        Pro_g_23.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_23.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_23.setOpaque(true);
        Pro_g_23.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_23.setRequestFocusEnabled(false);
        Pro_g_23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_23MouseClicked(evt);
            }
        });

        Pro_g_3.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_3.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_3.setText("2");
        Pro_g_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_3.setFocusable(false);
        Pro_g_3.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_3.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_3.setOpaque(true);
        Pro_g_3.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_3.setRequestFocusEnabled(false);
        Pro_g_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_3MouseClicked(evt);
            }
        });

        Pro_g_24.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_24.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_24.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_24.setText("2");
        Pro_g_24.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_24.setFocusable(false);
        Pro_g_24.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_24.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_24.setOpaque(true);
        Pro_g_24.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_24.setRequestFocusEnabled(false);
        Pro_g_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_24MouseClicked(evt);
            }
        });

        Pro_g_25.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_25.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_25.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_25.setText("1");
        Pro_g_25.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_25.setFocusable(false);
        Pro_g_25.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_25.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_25.setOpaque(true);
        Pro_g_25.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_25.setRequestFocusEnabled(false);
        Pro_g_25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_25MouseClicked(evt);
            }
        });

        Pro_g_26.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_26.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_26.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_26.setText("X");
        Pro_g_26.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_26.setFocusable(false);
        Pro_g_26.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_26.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_26.setOpaque(true);
        Pro_g_26.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_26.setRequestFocusEnabled(false);
        Pro_g_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_26MouseClicked(evt);
            }
        });

        Pro_g_27.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_27.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_27.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_27.setText("2");
        Pro_g_27.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_27.setFocusable(false);
        Pro_g_27.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_27.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_27.setOpaque(true);
        Pro_g_27.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_27.setRequestFocusEnabled(false);
        Pro_g_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_27MouseClicked(evt);
            }
        });

        Pro_g_28.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_28.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_28.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_28.setText("1");
        Pro_g_28.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_28.setFocusable(false);
        Pro_g_28.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_28.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_28.setOpaque(true);
        Pro_g_28.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_28.setRequestFocusEnabled(false);
        Pro_g_28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_28MouseClicked(evt);
            }
        });

        Pro_g_29.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_29.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_29.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_29.setText("X");
        Pro_g_29.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_29.setFocusable(false);
        Pro_g_29.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_29.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_29.setOpaque(true);
        Pro_g_29.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_29.setRequestFocusEnabled(false);
        Pro_g_29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_29MouseClicked(evt);
            }
        });

        Pro_g_30.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_30.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_30.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_30.setText("2");
        Pro_g_30.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_30.setFocusable(false);
        Pro_g_30.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_30.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_30.setOpaque(true);
        Pro_g_30.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_30.setRequestFocusEnabled(false);
        Pro_g_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_30MouseClicked(evt);
            }
        });

        Pro_g_31.setBackground(new java.awt.Color(255, 255, 255));
        Pro_g_31.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Pro_g_31.setForeground(new java.awt.Color(255, 199, 199));
        Pro_g_31.setText("1");
        Pro_g_31.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 1, 1));
        Pro_g_31.setFocusable(false);
        Pro_g_31.setMaximumSize(new java.awt.Dimension(13, 13));
        Pro_g_31.setMinimumSize(new java.awt.Dimension(13, 13));
        Pro_g_31.setOpaque(true);
        Pro_g_31.setPreferredSize(new java.awt.Dimension(13, 13));
        Pro_g_31.setRequestFocusEnabled(false);
        Pro_g_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro_g_31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_40, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_41, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_42, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_19, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_21, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_22, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_24, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_25, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_26, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_27, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_28, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_29, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_30, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_31, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_32, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_33, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_34, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_35, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_36, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_37, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_38, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_39, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_13, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_15, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pro_g_16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_17, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Pro_g_18, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_27, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_35, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_36, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_38, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_37, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pro_g_41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pro_g_42, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Pro_g_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_4MouseClicked
        ChangeColor(this.Pro_g_4,1,0);
    }//GEN-LAST:event_Pro_g_4MouseClicked

    private void Pro_g_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_5MouseClicked
        ChangeColor(this.Pro_g_5,1,1);
    }//GEN-LAST:event_Pro_g_5MouseClicked

    private void Pro_g_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_6MouseClicked
        ChangeColor(this.Pro_g_6,1,2);
    }//GEN-LAST:event_Pro_g_6MouseClicked

    private void Pro_g_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_7MouseClicked
        ChangeColor(this.Pro_g_7,2,0);
    }//GEN-LAST:event_Pro_g_7MouseClicked

    private void Pro_g_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_8MouseClicked
        ChangeColor(this.Pro_g_8,2,1);
    }//GEN-LAST:event_Pro_g_8MouseClicked

    private void Pro_g_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_9MouseClicked
        ChangeColor(this.Pro_g_9,2,2);
    }//GEN-LAST:event_Pro_g_9MouseClicked

    private void Pro_g_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_10MouseClicked
        ChangeColor(this.Pro_g_10,3,0);
    }//GEN-LAST:event_Pro_g_10MouseClicked

    private void Pro_g_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_11MouseClicked
        ChangeColor(this.Pro_g_11,3,1);
    }//GEN-LAST:event_Pro_g_11MouseClicked

    private void Pro_g_32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_32MouseClicked
        ChangeColor(this.Pro_g_32,10,1);
    }//GEN-LAST:event_Pro_g_32MouseClicked

    private void Pro_g_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_12MouseClicked
        ChangeColor(this.Pro_g_12,3,2);
    }//GEN-LAST:event_Pro_g_12MouseClicked

    private void Pro_g_33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_33MouseClicked
        ChangeColor(this.Pro_g_33,10,2);
    }//GEN-LAST:event_Pro_g_33MouseClicked

    private void Pro_g_34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_34MouseClicked
        ChangeColor(this.Pro_g_34,11,0);
    }//GEN-LAST:event_Pro_g_34MouseClicked

    private void Pro_g_35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_35MouseClicked
        ChangeColor(this.Pro_g_35,11,1);
    }//GEN-LAST:event_Pro_g_35MouseClicked

    private void Pro_g_36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_36MouseClicked
        ChangeColor(this.Pro_g_36,11,2);
    }//GEN-LAST:event_Pro_g_36MouseClicked

    private void Pro_g_37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_37MouseClicked
        ChangeColor(this.Pro_g_37,12,0);
    }//GEN-LAST:event_Pro_g_37MouseClicked

    private void Pro_g_38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_38MouseClicked
        ChangeColor(this.Pro_g_38,12,1);
    }//GEN-LAST:event_Pro_g_38MouseClicked

    private void Pro_g_39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_39MouseClicked
        ChangeColor(this.Pro_g_39,12,2);
    }//GEN-LAST:event_Pro_g_39MouseClicked

    private void Pro_g_40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_40MouseClicked
        ChangeColor(this.Pro_g_40,13,0);
    }//GEN-LAST:event_Pro_g_40MouseClicked

    private void Pro_g_41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_41MouseClicked
        ChangeColor(this.Pro_g_41,13,1);
    }//GEN-LAST:event_Pro_g_41MouseClicked

    private void Pro_g_42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_42MouseClicked
        ChangeColor(this.Pro_g_42,13,2);
    }//GEN-LAST:event_Pro_g_42MouseClicked

    private void Pro_g_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_2MouseClicked
        ChangeColor(this.Pro_g_2,0,1);
    }//GEN-LAST:event_Pro_g_2MouseClicked

    private void Pro_g_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_13MouseClicked
        ChangeColor(this.Pro_g_13,4,0);
    }//GEN-LAST:event_Pro_g_13MouseClicked

    private void Pro_g_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_14MouseClicked
        ChangeColor(this.Pro_g_14,4,1);
    }//GEN-LAST:event_Pro_g_14MouseClicked

    private void Pro_g_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_15MouseClicked
        ChangeColor(this.Pro_g_15,4,2);
    }//GEN-LAST:event_Pro_g_15MouseClicked

    private void Pro_g_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_16MouseClicked

        ChangeColor(this.Pro_g_16,5,0);
    }//GEN-LAST:event_Pro_g_16MouseClicked

    private void Pro_g_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_17MouseClicked

        ChangeColor(this.Pro_g_17,5,1);
    }//GEN-LAST:event_Pro_g_17MouseClicked

    private void Pro_g_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_18MouseClicked
        ChangeColor(this.Pro_g_18,5,2);
    }//GEN-LAST:event_Pro_g_18MouseClicked

    private void Pro_g_19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_19MouseClicked
        ChangeColor(this.Pro_g_19,6,0);
    }//GEN-LAST:event_Pro_g_19MouseClicked

    private void Pro_g_20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_20MouseClicked
        ChangeColor(this.Pro_g_20,6,1);
    }//GEN-LAST:event_Pro_g_20MouseClicked

    private void Pro_g_21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_21MouseClicked
        ChangeColor(this.Pro_g_21,6,2);
    }//GEN-LAST:event_Pro_g_21MouseClicked

    private void Pro_g_22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_22MouseClicked
        ChangeColor(this.Pro_g_22,7,0);
    }//GEN-LAST:event_Pro_g_22MouseClicked

    private void Pro_g_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_1MouseClicked

        ChangeColor(this.Pro_g_1,0,0);

    }//GEN-LAST:event_Pro_g_1MouseClicked

    private void Pro_g_23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_23MouseClicked
        ChangeColor(this.Pro_g_23,7,1);
    }//GEN-LAST:event_Pro_g_23MouseClicked

    private void Pro_g_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_3MouseClicked
        ChangeColor(this.Pro_g_3,0,2);
    }//GEN-LAST:event_Pro_g_3MouseClicked

    private void Pro_g_24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_24MouseClicked
        ChangeColor(this.Pro_g_24,7,2);
    }//GEN-LAST:event_Pro_g_24MouseClicked

    private void Pro_g_25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_25MouseClicked
        ChangeColor(this.Pro_g_25,8,0);
    }//GEN-LAST:event_Pro_g_25MouseClicked

    private void Pro_g_26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_26MouseClicked
        ChangeColor(this.Pro_g_26,8,1);
    }//GEN-LAST:event_Pro_g_26MouseClicked

    private void Pro_g_27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_27MouseClicked
        ChangeColor(this.Pro_g_27,8,2);
    }//GEN-LAST:event_Pro_g_27MouseClicked

    private void Pro_g_28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_28MouseClicked
        ChangeColor(this.Pro_g_28,9,0);
    }//GEN-LAST:event_Pro_g_28MouseClicked

    private void Pro_g_29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_29MouseClicked
        ChangeColor(this.Pro_g_29,9,1);
    }//GEN-LAST:event_Pro_g_29MouseClicked

    private void Pro_g_30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_30MouseClicked
        ChangeColor(this.Pro_g_30,9,2);
    }//GEN-LAST:event_Pro_g_30MouseClicked

    private void Pro_g_31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro_g_31MouseClicked
        ChangeColor(this.Pro_g_31,10,0);
    }//GEN-LAST:event_Pro_g_31MouseClicked
    
    private void ChangeColor(javax.swing.JLabel b, int f, int c) {
         if (negro.getRGB()== b.getForeground().getRGB()) {
            
            b.setForeground(rosa);
        
        }else{
        
            b.setForeground(negro);
        }//To change body of generated methods, choose Tools | Templates.

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pro_g_1;
    private javax.swing.JLabel Pro_g_10;
    private javax.swing.JLabel Pro_g_11;
    private javax.swing.JLabel Pro_g_12;
    private javax.swing.JLabel Pro_g_13;
    private javax.swing.JLabel Pro_g_14;
    private javax.swing.JLabel Pro_g_15;
    private javax.swing.JLabel Pro_g_16;
    private javax.swing.JLabel Pro_g_17;
    private javax.swing.JLabel Pro_g_18;
    private javax.swing.JLabel Pro_g_19;
    private javax.swing.JLabel Pro_g_2;
    private javax.swing.JLabel Pro_g_20;
    private javax.swing.JLabel Pro_g_21;
    private javax.swing.JLabel Pro_g_22;
    private javax.swing.JLabel Pro_g_23;
    private javax.swing.JLabel Pro_g_24;
    private javax.swing.JLabel Pro_g_25;
    private javax.swing.JLabel Pro_g_26;
    private javax.swing.JLabel Pro_g_27;
    private javax.swing.JLabel Pro_g_28;
    private javax.swing.JLabel Pro_g_29;
    private javax.swing.JLabel Pro_g_3;
    private javax.swing.JLabel Pro_g_30;
    private javax.swing.JLabel Pro_g_31;
    private javax.swing.JLabel Pro_g_32;
    private javax.swing.JLabel Pro_g_33;
    private javax.swing.JLabel Pro_g_34;
    private javax.swing.JLabel Pro_g_35;
    private javax.swing.JLabel Pro_g_36;
    private javax.swing.JLabel Pro_g_37;
    private javax.swing.JLabel Pro_g_38;
    private javax.swing.JLabel Pro_g_39;
    private javax.swing.JLabel Pro_g_4;
    private javax.swing.JLabel Pro_g_40;
    private javax.swing.JLabel Pro_g_41;
    private javax.swing.JLabel Pro_g_42;
    private javax.swing.JLabel Pro_g_5;
    private javax.swing.JLabel Pro_g_6;
    private javax.swing.JLabel Pro_g_7;
    private javax.swing.JLabel Pro_g_8;
    private javax.swing.JLabel Pro_g_9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
