/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnqui;

import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author Nacho
 */
public class PorPartidos extends javax.swing.JPanel {
     JTextField[][] partidos;
    /**
     * Creates new form LabPartidos2
     */
    public PorPartidos() {
        initComponents();
        setpartidos();
    }

        public final void setpartidos(){
         partidos = new javax.swing.JTextField[][]{  {Por11,Por12,Por13},
            {Por21,Por22,Por23},
            {Por31,Por32,Por33},
            {Por41,Por42,Por43},
            {Por51,Por52,Por53},
            {Por61,Por62,Por63},
            {Por71,Por72,Por73},
            {Por81,Por82,Por83},
            {Por91,Por92,Por93},
            {Por101,Por102,Por103},
            {Por111,Por112,Por113},
            {Por121,Por122,Por123},
            {Por131,Por132,Por133},
            {Por141,Por142,Por143}};
    
    }
        
    public void setPartidos(int j, int i, String equipo){

            partidos[j][i].setText(equipo);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Por111 = new javax.swing.JTextField();
        Por112 = new javax.swing.JTextField();
        Por121 = new javax.swing.JTextField();
        Por122 = new javax.swing.JTextField();
        Por131 = new javax.swing.JTextField();
        Por132 = new javax.swing.JTextField();
        Por141 = new javax.swing.JTextField();
        Por142 = new javax.swing.JTextField();
        Por72 = new javax.swing.JTextField();
        Por22 = new javax.swing.JTextField();
        Por81 = new javax.swing.JTextField();
        Por82 = new javax.swing.JTextField();
        Por91 = new javax.swing.JTextField();
        Por31 = new javax.swing.JTextField();
        Por92 = new javax.swing.JTextField();
        Por32 = new javax.swing.JTextField();
        Por101 = new javax.swing.JTextField();
        Por41 = new javax.swing.JTextField();
        Por51 = new javax.swing.JTextField();
        Por52 = new javax.swing.JTextField();
        Por11 = new javax.swing.JTextField();
        Por61 = new javax.swing.JTextField();
        Por62 = new javax.swing.JTextField();
        Por12 = new javax.swing.JTextField();
        Por71 = new javax.swing.JTextField();
        Por21 = new javax.swing.JTextField();
        Por102 = new javax.swing.JTextField();
        Por42 = new javax.swing.JTextField();
        Por53 = new javax.swing.JTextField();
        Por63 = new javax.swing.JTextField();
        Por113 = new javax.swing.JTextField();
        Por13 = new javax.swing.JTextField();
        Por123 = new javax.swing.JTextField();
        Por133 = new javax.swing.JTextField();
        Por103 = new javax.swing.JTextField();
        Por43 = new javax.swing.JTextField();
        Por143 = new javax.swing.JTextField();
        Por73 = new javax.swing.JTextField();
        Por23 = new javax.swing.JTextField();
        Por83 = new javax.swing.JTextField();
        Por93 = new javax.swing.JTextField();
        Por33 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(230, 250));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        Por111.setEditable(false);
        Por111.setBackground(new java.awt.Color(255, 255, 204));
        Por111.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por111.setForeground(new java.awt.Color(102, 102, 102));
        Por111.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por111.setBorder(null);
        Por111.setFocusable(false);
        Por111.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por111.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por111ActionPerformed(evt);
            }
        });

        Por112.setEditable(false);
        Por112.setBackground(new java.awt.Color(255, 255, 204));
        Por112.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por112.setForeground(new java.awt.Color(102, 102, 102));
        Por112.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por112.setBorder(null);
        Por112.setFocusable(false);
        Por112.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por112.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por112ActionPerformed(evt);
            }
        });

        Por121.setEditable(false);
        Por121.setBackground(new java.awt.Color(255, 255, 204));
        Por121.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por121.setForeground(new java.awt.Color(102, 102, 102));
        Por121.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por121.setBorder(null);
        Por121.setFocusable(false);
        Por121.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por121.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por121ActionPerformed(evt);
            }
        });

        Por122.setEditable(false);
        Por122.setBackground(new java.awt.Color(255, 255, 204));
        Por122.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por122.setForeground(new java.awt.Color(102, 102, 102));
        Por122.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por122.setBorder(null);
        Por122.setFocusable(false);
        Por122.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por122.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por122ActionPerformed(evt);
            }
        });

        Por131.setEditable(false);
        Por131.setBackground(new java.awt.Color(255, 255, 204));
        Por131.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por131.setForeground(new java.awt.Color(102, 102, 102));
        Por131.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por131.setBorder(null);
        Por131.setFocusable(false);
        Por131.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por131.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por131ActionPerformed(evt);
            }
        });

        Por132.setEditable(false);
        Por132.setBackground(new java.awt.Color(255, 255, 204));
        Por132.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por132.setForeground(new java.awt.Color(102, 102, 102));
        Por132.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por132.setBorder(null);
        Por132.setFocusable(false);
        Por132.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por132.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por132ActionPerformed(evt);
            }
        });

        Por141.setEditable(false);
        Por141.setBackground(new java.awt.Color(255, 255, 204));
        Por141.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por141.setForeground(new java.awt.Color(102, 102, 102));
        Por141.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por141.setBorder(null);
        Por141.setFocusable(false);
        Por141.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por141.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por141.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por141ActionPerformed(evt);
            }
        });

        Por142.setEditable(false);
        Por142.setBackground(new java.awt.Color(255, 255, 204));
        Por142.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por142.setForeground(new java.awt.Color(102, 102, 102));
        Por142.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por142.setBorder(null);
        Por142.setFocusable(false);
        Por142.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por142.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por142.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por142ActionPerformed(evt);
            }
        });

        Por72.setEditable(false);
        Por72.setBackground(new java.awt.Color(255, 255, 204));
        Por72.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por72.setForeground(new java.awt.Color(102, 102, 102));
        Por72.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por72.setBorder(null);
        Por72.setFocusable(false);
        Por72.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por72.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por72ActionPerformed(evt);
            }
        });

        Por22.setEditable(false);
        Por22.setBackground(new java.awt.Color(255, 255, 204));
        Por22.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por22.setForeground(new java.awt.Color(102, 102, 102));
        Por22.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por22.setBorder(null);
        Por22.setFocusable(false);
        Por22.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por22.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por22ActionPerformed(evt);
            }
        });

        Por81.setEditable(false);
        Por81.setBackground(new java.awt.Color(255, 255, 204));
        Por81.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por81.setForeground(new java.awt.Color(102, 102, 102));
        Por81.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por81.setBorder(null);
        Por81.setFocusable(false);
        Por81.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por81.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por81ActionPerformed(evt);
            }
        });

        Por82.setEditable(false);
        Por82.setBackground(new java.awt.Color(255, 255, 204));
        Por82.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por82.setForeground(new java.awt.Color(102, 102, 102));
        Por82.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por82.setBorder(null);
        Por82.setFocusable(false);
        Por82.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por82.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por82ActionPerformed(evt);
            }
        });

        Por91.setEditable(false);
        Por91.setBackground(new java.awt.Color(255, 255, 204));
        Por91.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por91.setForeground(new java.awt.Color(102, 102, 102));
        Por91.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por91.setBorder(null);
        Por91.setFocusable(false);
        Por91.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por91.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por91ActionPerformed(evt);
            }
        });

        Por31.setEditable(false);
        Por31.setBackground(new java.awt.Color(255, 255, 204));
        Por31.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por31.setForeground(new java.awt.Color(102, 102, 102));
        Por31.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por31.setBorder(null);
        Por31.setFocusable(false);
        Por31.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por31.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por31ActionPerformed(evt);
            }
        });

        Por92.setEditable(false);
        Por92.setBackground(new java.awt.Color(255, 255, 204));
        Por92.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por92.setForeground(new java.awt.Color(102, 102, 102));
        Por92.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por92.setBorder(null);
        Por92.setFocusable(false);
        Por92.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por92.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por92ActionPerformed(evt);
            }
        });

        Por32.setEditable(false);
        Por32.setBackground(new java.awt.Color(255, 255, 204));
        Por32.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por32.setForeground(new java.awt.Color(102, 102, 102));
        Por32.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por32.setBorder(null);
        Por32.setFocusable(false);
        Por32.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por32.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por32ActionPerformed(evt);
            }
        });

        Por101.setEditable(false);
        Por101.setBackground(new java.awt.Color(255, 255, 204));
        Por101.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por101.setForeground(new java.awt.Color(102, 102, 102));
        Por101.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por101.setBorder(null);
        Por101.setFocusable(false);
        Por101.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por101.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por101ActionPerformed(evt);
            }
        });

        Por41.setEditable(false);
        Por41.setBackground(new java.awt.Color(255, 255, 204));
        Por41.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por41.setForeground(new java.awt.Color(102, 102, 102));
        Por41.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por41.setBorder(null);
        Por41.setFocusable(false);
        Por41.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por41.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por41ActionPerformed(evt);
            }
        });

        Por51.setEditable(false);
        Por51.setBackground(new java.awt.Color(255, 255, 204));
        Por51.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por51.setForeground(new java.awt.Color(102, 102, 102));
        Por51.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por51.setBorder(null);
        Por51.setFocusable(false);
        Por51.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por51.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por51ActionPerformed(evt);
            }
        });

        Por52.setEditable(false);
        Por52.setBackground(new java.awt.Color(255, 255, 204));
        Por52.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por52.setForeground(new java.awt.Color(102, 102, 102));
        Por52.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por52.setBorder(null);
        Por52.setFocusable(false);
        Por52.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por52.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por52ActionPerformed(evt);
            }
        });

        Por11.setEditable(false);
        Por11.setBackground(new java.awt.Color(255, 255, 204));
        Por11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por11.setForeground(new java.awt.Color(102, 102, 102));
        Por11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por11.setBorder(null);
        Por11.setFocusable(false);
        Por11.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por11.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por11ActionPerformed(evt);
            }
        });

        Por61.setEditable(false);
        Por61.setBackground(new java.awt.Color(255, 255, 204));
        Por61.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por61.setForeground(new java.awt.Color(102, 102, 102));
        Por61.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por61.setBorder(null);
        Por61.setFocusable(false);
        Por61.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por61.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por61ActionPerformed(evt);
            }
        });

        Por62.setEditable(false);
        Por62.setBackground(new java.awt.Color(255, 255, 204));
        Por62.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por62.setForeground(new java.awt.Color(102, 102, 102));
        Por62.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por62.setBorder(null);
        Por62.setFocusable(false);
        Por62.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por62.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por62ActionPerformed(evt);
            }
        });

        Por12.setEditable(false);
        Por12.setBackground(new java.awt.Color(255, 255, 204));
        Por12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por12.setForeground(new java.awt.Color(102, 102, 102));
        Por12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por12.setBorder(null);
        Por12.setFocusable(false);
        Por12.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por12.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por12ActionPerformed(evt);
            }
        });

        Por71.setEditable(false);
        Por71.setBackground(new java.awt.Color(255, 255, 204));
        Por71.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por71.setForeground(new java.awt.Color(102, 102, 102));
        Por71.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por71.setBorder(null);
        Por71.setFocusable(false);
        Por71.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por71.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por71ActionPerformed(evt);
            }
        });

        Por21.setEditable(false);
        Por21.setBackground(new java.awt.Color(255, 255, 204));
        Por21.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por21.setForeground(new java.awt.Color(102, 102, 102));
        Por21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por21.setBorder(null);
        Por21.setFocusable(false);
        Por21.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por21.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por21ActionPerformed(evt);
            }
        });

        Por102.setEditable(false);
        Por102.setBackground(new java.awt.Color(255, 255, 204));
        Por102.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por102.setForeground(new java.awt.Color(102, 102, 102));
        Por102.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por102.setBorder(null);
        Por102.setFocusable(false);
        Por102.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por102.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por102ActionPerformed(evt);
            }
        });

        Por42.setEditable(false);
        Por42.setBackground(new java.awt.Color(255, 255, 204));
        Por42.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por42.setForeground(new java.awt.Color(102, 102, 102));
        Por42.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por42.setBorder(null);
        Por42.setFocusable(false);
        Por42.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por42.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por42ActionPerformed(evt);
            }
        });

        Por53.setEditable(false);
        Por53.setBackground(new java.awt.Color(255, 255, 204));
        Por53.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por53.setForeground(new java.awt.Color(102, 102, 102));
        Por53.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por53.setBorder(null);
        Por53.setFocusable(false);
        Por53.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por53.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por53ActionPerformed(evt);
            }
        });

        Por63.setEditable(false);
        Por63.setBackground(new java.awt.Color(255, 255, 204));
        Por63.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por63.setForeground(new java.awt.Color(102, 102, 102));
        Por63.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por63.setBorder(null);
        Por63.setFocusable(false);
        Por63.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por63.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por63ActionPerformed(evt);
            }
        });

        Por113.setEditable(false);
        Por113.setBackground(new java.awt.Color(255, 255, 204));
        Por113.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por113.setForeground(new java.awt.Color(102, 102, 102));
        Por113.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por113.setBorder(null);
        Por113.setFocusable(false);
        Por113.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por113.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por113ActionPerformed(evt);
            }
        });

        Por13.setEditable(false);
        Por13.setBackground(new java.awt.Color(255, 255, 204));
        Por13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por13.setForeground(new java.awt.Color(102, 102, 102));
        Por13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por13.setBorder(null);
        Por13.setFocusable(false);
        Por13.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por13.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por13ActionPerformed(evt);
            }
        });

        Por123.setEditable(false);
        Por123.setBackground(new java.awt.Color(255, 255, 204));
        Por123.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por123.setForeground(new java.awt.Color(102, 102, 102));
        Por123.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por123.setBorder(null);
        Por123.setFocusable(false);
        Por123.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por123.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por123ActionPerformed(evt);
            }
        });

        Por133.setEditable(false);
        Por133.setBackground(new java.awt.Color(255, 255, 204));
        Por133.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por133.setForeground(new java.awt.Color(102, 102, 102));
        Por133.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por133.setBorder(null);
        Por133.setFocusable(false);
        Por133.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por133.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por133ActionPerformed(evt);
            }
        });

        Por103.setEditable(false);
        Por103.setBackground(new java.awt.Color(255, 255, 204));
        Por103.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por103.setForeground(new java.awt.Color(102, 102, 102));
        Por103.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por103.setBorder(null);
        Por103.setFocusable(false);
        Por103.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por103.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por103ActionPerformed(evt);
            }
        });

        Por43.setEditable(false);
        Por43.setBackground(new java.awt.Color(255, 255, 204));
        Por43.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por43.setForeground(new java.awt.Color(102, 102, 102));
        Por43.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por43.setBorder(null);
        Por43.setFocusable(false);
        Por43.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por43.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por43ActionPerformed(evt);
            }
        });

        Por143.setEditable(false);
        Por143.setBackground(new java.awt.Color(255, 255, 204));
        Por143.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por143.setForeground(new java.awt.Color(102, 102, 102));
        Por143.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por143.setBorder(null);
        Por143.setFocusable(false);
        Por143.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por143.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por143.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por143ActionPerformed(evt);
            }
        });

        Por73.setEditable(false);
        Por73.setBackground(new java.awt.Color(255, 255, 204));
        Por73.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por73.setForeground(new java.awt.Color(102, 102, 102));
        Por73.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por73.setBorder(null);
        Por73.setFocusable(false);
        Por73.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por73.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por73ActionPerformed(evt);
            }
        });

        Por23.setEditable(false);
        Por23.setBackground(new java.awt.Color(255, 255, 204));
        Por23.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por23.setForeground(new java.awt.Color(102, 102, 102));
        Por23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por23.setBorder(null);
        Por23.setFocusable(false);
        Por23.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por23.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por23ActionPerformed(evt);
            }
        });

        Por83.setEditable(false);
        Por83.setBackground(new java.awt.Color(255, 255, 204));
        Por83.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por83.setForeground(new java.awt.Color(102, 102, 102));
        Por83.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por83.setBorder(null);
        Por83.setFocusable(false);
        Por83.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por83.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por83ActionPerformed(evt);
            }
        });

        Por93.setEditable(false);
        Por93.setBackground(new java.awt.Color(255, 255, 204));
        Por93.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por93.setForeground(new java.awt.Color(102, 102, 102));
        Por93.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por93.setBorder(null);
        Por93.setFocusable(false);
        Por93.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por93.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por93ActionPerformed(evt);
            }
        });

        Por33.setEditable(false);
        Por33.setBackground(new java.awt.Color(255, 255, 204));
        Por33.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Por33.setForeground(new java.awt.Color(102, 102, 102));
        Por33.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Por33.setBorder(null);
        Por33.setFocusable(false);
        Por33.setMargin(new java.awt.Insets(6, 4, 2, 2));
        Por33.setSelectionColor(new java.awt.Color(102, 102, 102));
        Por33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Por33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Por141, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Por142, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por71, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por72, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por61, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por62, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por81, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por82, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por111, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por112, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por101, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por102, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por121, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por122, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por51, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por91, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por92, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Por131, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Por132, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Por143, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Por23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por43, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por73, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por63, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por83, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por113, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por103, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por123, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por53, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por93, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Por133, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Por13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por43, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Por53, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por63, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por73, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por83, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Por93, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por103, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por113, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Por123, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por133, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Por143, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por42, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por52, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por51, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Por61, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por62, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por71, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por72, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por82, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por81, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por91, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por92, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por102, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por101, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por111, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por112, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por122, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por121, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Por131, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por132, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Por142, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Por141, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Por51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por51ActionPerformed

    private void Por52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por52ActionPerformed

    private void Por11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por11ActionPerformed

    private void Por61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por61ActionPerformed

    private void Por62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por62ActionPerformed

    private void Por12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por12ActionPerformed

    private void Por71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por71ActionPerformed

    private void Por21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por21ActionPerformed

    private void Por72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por72ActionPerformed

    private void Por22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por22ActionPerformed

    private void Por81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por81ActionPerformed

    private void Por82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por82ActionPerformed

    private void Por91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por91ActionPerformed

    private void Por31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por31ActionPerformed

    private void Por92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por92ActionPerformed

    private void Por32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por32ActionPerformed

    private void Por101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por101ActionPerformed

    private void Por41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por41ActionPerformed

    private void Por102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por102ActionPerformed

    private void Por42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por42ActionPerformed

    private void Por111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por111ActionPerformed

    private void Por112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por112ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por112ActionPerformed

    private void Por121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por121ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por121ActionPerformed

    private void Por122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por122ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por122ActionPerformed

    private void Por131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por131ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por131ActionPerformed

    private void Por132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por132ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por132ActionPerformed

    private void Por141ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por141ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por141ActionPerformed

    private void Por142ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por142ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por142ActionPerformed

    private void Por53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por53ActionPerformed

    private void Por63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por63ActionPerformed

    private void Por113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por113ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por113ActionPerformed

    private void Por13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por13ActionPerformed

    private void Por123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por123ActionPerformed

    private void Por133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por133ActionPerformed

    private void Por103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por103ActionPerformed

    private void Por43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por43ActionPerformed

    private void Por143ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por143ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por143ActionPerformed

    private void Por73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por73ActionPerformed

    private void Por23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por23ActionPerformed

    private void Por83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por83ActionPerformed

    private void Por93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por93ActionPerformed

    private void Por33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Por33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Por33ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Por101;
    private javax.swing.JTextField Por102;
    private javax.swing.JTextField Por103;
    private javax.swing.JTextField Por11;
    private javax.swing.JTextField Por111;
    private javax.swing.JTextField Por112;
    private javax.swing.JTextField Por113;
    private javax.swing.JTextField Por12;
    private javax.swing.JTextField Por121;
    private javax.swing.JTextField Por122;
    private javax.swing.JTextField Por123;
    private javax.swing.JTextField Por13;
    private javax.swing.JTextField Por131;
    private javax.swing.JTextField Por132;
    private javax.swing.JTextField Por133;
    private javax.swing.JTextField Por141;
    private javax.swing.JTextField Por142;
    private javax.swing.JTextField Por143;
    private javax.swing.JTextField Por21;
    private javax.swing.JTextField Por22;
    private javax.swing.JTextField Por23;
    private javax.swing.JTextField Por31;
    private javax.swing.JTextField Por32;
    private javax.swing.JTextField Por33;
    private javax.swing.JTextField Por41;
    private javax.swing.JTextField Por42;
    private javax.swing.JTextField Por43;
    private javax.swing.JTextField Por51;
    private javax.swing.JTextField Por52;
    private javax.swing.JTextField Por53;
    private javax.swing.JTextField Por61;
    private javax.swing.JTextField Por62;
    private javax.swing.JTextField Por63;
    private javax.swing.JTextField Por71;
    private javax.swing.JTextField Por72;
    private javax.swing.JTextField Por73;
    private javax.swing.JTextField Por81;
    private javax.swing.JTextField Por82;
    private javax.swing.JTextField Por83;
    private javax.swing.JTextField Por91;
    private javax.swing.JTextField Por92;
    private javax.swing.JTextField Por93;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
